#A docker compose file with networks and exteral volumes defined.
version: '3.8'
services:
  webapp:
    image: mylandmarktech/spring-boot-mongo
#    restart: always
    ports:
      - 3000:8080
    networks:
      - tesla
    environment:
      - MONGO_DB_HOSTNAME=mongodb
      - MONGO_DB_USERNAME=devdb
      - MONGO_DB_PASSWORD=dev@123
  mongodb:
       image: mongo
 #      restart: always
       volumes:
         - db-data:/data/db
       networks:
         - tesla
       environment:
         - MONGO_INITDB_ROOT_USERNAME=devdb
         - MONGO_INITDB_ROOT_PASSWORD=dev@123
volumes:
   db-data:
     external: false
networks:
  tesla:
    external: true
